-- MySQL Script generated by MySQL Workbench
-- Mon Feb  6 10:53:13 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema budget
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema budget
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `budget` DEFAULT CHARACTER SET utf8 ;
USE `budget` ;

-- -----------------------------------------------------
-- Table `company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `company` (
  `id` BIGINT(11) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `cnpj` VARCHAR(255) NOT NULL,
  `creation_date` DATETIME NOT NULL,
  `last_update_date` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user` (
  `id` BIGINT(11) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `inactive` TINYINT NOT NULL,
  `creation_date` DATETIME NOT NULL,
  `last_update_date` DATETIME NOT NULL,
  `Company_id` BIGINT(11) NOT NULL,
  PRIMARY KEY (`id`, `Company_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_User_Company1_idx` (`Company_id` ASC) VISIBLE,
  CONSTRAINT `fk_User_Company1`
    FOREIGN KEY (`Company_id`)
    REFERENCES `company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `logo_company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logo_company` (
  `content_type` VARCHAR(255) NOT NULL,
  `file_name` VARCHAR(255) NOT NULL,
  `size` BIGINT(255) NOT NULL,
  `Company_id` BIGINT(11) NOT NULL,
  PRIMARY KEY (`Company_id`),
  CONSTRAINT `fk_logo_company_Company1`
    FOREIGN KEY (`Company_id`)
    REFERENCES `company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `account` (
  `id` BIGINT(11) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `balance` DOUBLE NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `inactive` TINYINT NOT NULL,
  `company_id` BIGINT(11) NOT NULL,
  PRIMARY KEY (`id`, `company_id`),
  INDEX `fk_bank_account_ company1_idx` (`company_id` ASC) VISIBLE,
  CONSTRAINT `fk_bank_account_ company1`
    FOREIGN KEY (`company_id`)
    REFERENCES `company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `profile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `profile` (
  `id` BIGINT(11) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `user_profile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user_profile` (
  `user_id` BIGINT(11) NOT NULL,
  `profile_id` BIGINT(11) NOT NULL,
  PRIMARY KEY (`user_id`, `profile_id`),
  INDEX `fk_user_has_profile_profile1_idx` (`profile_id` ASC) VISIBLE,
  INDEX `fk_user_has_profile_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_profile_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_profile_profile1`
    FOREIGN KEY (`profile_id`)
    REFERENCES `profile` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `permission` (
  `id` BIGINT(11) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `profile_permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `profile_permission` (
  `profile_id` BIGINT(11) NOT NULL,
  `permission_id` BIGINT(11) NOT NULL,
  PRIMARY KEY (`profile_id`, `permission_id`),
  INDEX `fk_profile_has_permission_permission1_idx` (`permission_id` ASC) VISIBLE,
  INDEX `fk_profile_has_permission_profile1_idx` (`profile_id` ASC) VISIBLE,
  CONSTRAINT `fk_profile_has_permission_profile1`
    FOREIGN KEY (`profile_id`)
    REFERENCES `profile` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_profile_has_permission_permission1`
    FOREIGN KEY (`permission_id`)
    REFERENCES `permission` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `parent_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parent_category` (
  `id` BIGINT(11) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `inactive` VARCHAR(45) NOT NULL,
  `creation_date` DATETIME NOT NULL,
  `company_id` BIGINT(11) NOT NULL,
  PRIMARY KEY (`id`, `company_id`),
  INDEX `fk_parent_category_ company1_idx` (`company_id` ASC) VISIBLE,
  CONSTRAINT `fk_parent_category_ company1`
    FOREIGN KEY (`company_id`)
    REFERENCES `company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `child_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `child_category` (
  `id` BIGINT(11) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `color` VARCHAR(45) NOT NULL,
  `creation_date` DATETIME NOT NULL,
  `inactive` TINYINT NOT NULL,
  `company_id` BIGINT(11) NOT NULL,
  `parent_category_id` BIGINT(11) NOT NULL,
  PRIMARY KEY (`id`, `company_id`, `parent_category_id`),
  INDEX `fk_category_ company1_idx` (`company_id` ASC) VISIBLE,
  INDEX `fk_child_category_parent_category1_idx` (`parent_category_id` ASC) VISIBLE,
  CONSTRAINT `fk_category_ company1`
    FOREIGN KEY (`company_id`)
    REFERENCES `company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_child_category_parent_category1`
    FOREIGN KEY (`parent_category_id`)
    REFERENCES `parent_category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '\n';


-- -----------------------------------------------------
-- Table `supplier_customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supplier_customer` (
  `id` BIGINT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `cnpj` VARCHAR(45) NULL,
  `cpf` VARCHAR(45) NULL,
  `inactive` TINYINT NOT NULL,
  `creation_date` DATETIME NOT NULL,
  `last_update_date` DATETIME NOT NULL,
  `company_id` BIGINT(11) NOT NULL,
  PRIMARY KEY (`id`, `company_id`),
  INDEX `fk_supplier_customer_ company1_idx` (`company_id` ASC) VISIBLE,
  CONSTRAINT `fk_supplier_customer_ company1`
    FOREIGN KEY (`company_id`)
    REFERENCES `company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `payment_method`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `payment_method` (
  `id` BIGINT(11) NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(255) NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `inactive` TINYINT NOT NULL,
  `company_id` BIGINT(11) NOT NULL,
  PRIMARY KEY (`id`, `company_id`),
  INDEX `fk_payment_method_ company1_idx` (`company_id` ASC) VISIBLE,
  CONSTRAINT `fk_payment_method_ company1`
    FOREIGN KEY (`company_id`)
    REFERENCES `company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `transaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `transaction` (
  `id` BIGINT(11) NOT NULL,
  `code` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `value` DOUBLE NOT NULL,
  `issue_date` DATE NOT NULL,
  `competence_date` DATE NOT NULL,
  `due_date` DATE NOT NULL,
  `creation_date` DATETIME NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `installments_total_number` INT NOT NULL,
  `installment_number` INT NOT NULL,
  `child_category_id` BIGINT(11) NOT NULL,
  `user_id` BIGINT(11) NOT NULL,
  `company_id` BIGINT(11) NOT NULL,
  `supplier_customer_id` BIGINT(11) NOT NULL,
  `payment_method_id` BIGINT(11) NOT NULL,
  `account_id` BIGINT(11) NOT NULL,
  PRIMARY KEY (`id`, `child_category_id`, `user_id`, `company_id`, `supplier_customer_id`, `payment_method_id`, `account_id`),
  UNIQUE INDEX `code_UNIQUE` (`code` ASC) VISIBLE,
  INDEX `fk_transaction_category1_idx` (`child_category_id` ASC) VISIBLE,
  INDEX `fk_transaction_user1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_transaction_ company1_idx` (`company_id` ASC) VISIBLE,
  INDEX `fk_transaction_supplier_customer1_idx` (`supplier_customer_id` ASC) VISIBLE,
  INDEX `fk_transaction_payment_method1_idx` (`payment_method_id` ASC) VISIBLE,
  INDEX `fk_transaction_account1_idx` (`account_id` ASC) VISIBLE,
  CONSTRAINT `fk_transaction_category1`
    FOREIGN KEY (`child_category_id`)
    REFERENCES `child_category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transaction_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transaction_ company1`
    FOREIGN KEY (`company_id`)
    REFERENCES `company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transaction_supplier_customer1`
    FOREIGN KEY (`supplier_customer_id`)
    REFERENCES `supplier_customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transaction_payment_method1`
    FOREIGN KEY (`payment_method_id`)
    REFERENCES `payment_method` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transaction_account1`
    FOREIGN KEY (`account_id`)
    REFERENCES `account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `user_photo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user_photo` (
  `content_type` VARCHAR(255) NOT NULL,
  `file_name` VARCHAR(255) NOT NULL,
  `size` BIGINT(255) NOT NULL,
  `user_id` BIGINT(11) NOT NULL,
  PRIMARY KEY (`user_id`),
  CONSTRAINT `fk_user_photo_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `payment` (
  `id` BIGINT(11) NOT NULL AUTO_INCREMENT,
  `value` DOUBLE NOT NULL,
  `payment_date` DATETIME NOT NULL,
  `installments_paid` JSON NOT NULL,
  `user_id` BIGINT(11) NOT NULL,
  `account_id` BIGINT(11) NOT NULL,
  `transaction_id` BIGINT(11) NOT NULL,
  `payment_method_id` BIGINT(11) NOT NULL,
  PRIMARY KEY (`id`, `user_id`, `account_id`, `transaction_id`, `payment_method_id`),
  INDEX `fk_payment_user1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_payment_account1_idx` (`account_id` ASC) VISIBLE,
  INDEX `fk_payment_transaction1_idx` (`transaction_id` ASC) VISIBLE,
  INDEX `fk_payment_payment_method1_idx` (`payment_method_id` ASC) VISIBLE,
  CONSTRAINT `fk_payment_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_payment_account1`
    FOREIGN KEY (`account_id`)
    REFERENCES `account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_payment_transaction1`
    FOREIGN KEY (`transaction_id`)
    REFERENCES `transaction` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_payment_payment_method1`
    FOREIGN KEY (`payment_method_id`)
    REFERENCES `payment_method` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `address_supplier_customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `address_supplier_customer` (
  `id` BIGINT(11) NOT NULL AUTO_INCREMENT,
  `city` VARCHAR(45) NULL,
  `uf` VARCHAR(45) NULL,
  `cep` VARCHAR(45) NULL,
  `place` VARCHAR(255) NULL,
  `number` INT NULL,
  `complement` VARCHAR(45) NULL,
  `district` VARCHAR(45) NULL,
  `supplier_customer_id` BIGINT(11) NOT NULL,
  PRIMARY KEY (`id`, `supplier_customer_id`),
  INDEX `fk_address_supplie_customer_supplier_customer1_idx` (`supplier_customer_id` ASC) VISIBLE,
  CONSTRAINT `fk_address_supplie_customer_supplier_customer1`
    FOREIGN KEY (`supplier_customer_id`)
    REFERENCES `supplier_customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `contact_supplier_customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `contact_supplier_customer` (
  `id` BIGINT(11) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `supplier_customer_id` BIGINT(11) NOT NULL,
  PRIMARY KEY (`id`, `supplier_customer_id`),
  INDEX `fk_contact_supplier_customer_supplier_customer1_idx` (`supplier_customer_id` ASC) VISIBLE,
  CONSTRAINT `fk_contact_supplier_customer_supplier_customer1`
    FOREIGN KEY (`supplier_customer_id`)
    REFERENCES `supplier_customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `contact_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `contact_user` (
  `id` BIGINT(11) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `user_id` BIGINT(11) NOT NULL,
  PRIMARY KEY (`id`, `user_id`),
  INDEX `fk_contact_user_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_contact_user_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `address_company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `address_company` (
  `id` BIGINT(11) NOT NULL AUTO_INCREMENT,
  `city` VARCHAR(45) NULL,
  `uf` VARCHAR(45) NULL,
  `cep` VARCHAR(45) NULL,
  `place` VARCHAR(255) NULL,
  `number` INT NULL,
  `complement` VARCHAR(45) NULL,
  `district` VARCHAR(45) NULL,
  `company_id` BIGINT(11) NOT NULL,
  PRIMARY KEY (`id`, `company_id`),
  INDEX `fk_address_company_ company1_idx` (`company_id` ASC) VISIBLE,
  CONSTRAINT `fk_address_company_ company1`
    FOREIGN KEY (`company_id`)
    REFERENCES `company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
